- name: Checkmarx CxFlow Action
  # You may pin to the exact commit or the version.
  # uses: checkmarx-ts/checkmarx-cxflow-github-action@fe2a395cbbee31268470d92b6c53ebc483005f0f
  uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1
  with:
    # Provide Checkmarx URL
    checkmarx_url: # default is 
    # Select a Checkmarx Team
    team: # default is /CxServer/SP/Company
    # Provide Checkmarx Username
    checkmarx_username: # default is 
    # Provide Checkmarx Password
    checkmarx_password: # default is 
    # Provide Checkmarx Client Secret
    checkmarx_client_secret: # default is 
    # Select a Checkmarx Project
    project: # default is 
    # Select an Application Name used by downstream bug tracker systems
    app: # optional, default is SampleApp
    # Select a Checkmarx Preset
    preset: # optional, default is Checkmarx Default
    # Break build based on Checkmarx findings?
    break_build: # optional
    # Bug tracker for the scan results.
    bug_tracker: # optional, default is Sarif
    # Incremental Scans?
    incremental: # optional, default is true
    # Additional CLI parameters
    params: # optional, default is 
    # GitHub API Token
    github_token: # optional, default is ${{ github.token }}
    # Vulnerability Scanners (sast, sca, ast, cxgo)
    scanners: # default is 
    # Provide SCA API URL
    sca_api_url: # optional, default is https://api.scacheckmarx.com
    # Provide SCA APP URL
    sca_app_url: # optional, default is https://sca.scacheckmarx.com
    # Provide SCA Access Control URL
    sca_access_control_url: # optional, default is https://platform.checkmarx.net
    # Provide SCA Tenant
    sca_tenant: # optional, default is 
    # Provide SCA Username
    sca_username: # optional, default is 
    # Provide SCA Password
    sca_password: # optional, default is 
    # Provide CxGo Client Secret
    cxgo_client_secret: # optional, default is 
    # Provide CxGo API URL
    cxgo_base_url: # optional, default is https://api.checkmarx.net
    # Provide CxGo Portal URL
    cxgo_portal_url: # optional, default is https://cloud.checkmarx.net
    # Provide AST API URL
    ast_api_url: # optional, default is 
    # Provide AST WebApp URL
    ast_webapp_url: # optional, default is 
    # Provide AST Client ID
    ast_client_id: # optional, default is 
    # Provide AST Client Secret
    ast_client_secret: # optional, default is 

# This workflow integrates Scan with GitHub's code scanning feature
# Scan is a free open-source security tool for modern DevOps teams from ShiftLeft
# Visit https://slscan.io/en/latest/integrations/code-scan for help
name: SL Scan

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on: push

jobs:
  Scan-Build:
    # Scan runs on ubuntu, mac and windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Instructions
    # 1. Setup JDK, Node.js, Python etc depending on your project type
    # 2. Compile or build the project before invoking scan
    #    Example: mvn compile, or npm install or pip install goes here
    # 3. Invoke Scan with the github token. Leave the workspace empty to use relative url

    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports
        # Scan auto-detects the languages in your project. To override uncomment the below variable and set the type
        # type: credscan,java
        # type: python

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports

